env:
  browser: true
  node: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "react/prop-types": 0,
  "@typescript-eslint/ban-ts-comment": 0,
  "@typescript-eslint/no-explicit-any": 0
}
settings:
  react:
    pragma: "React"
    version: "detect"
