env:
  browser: true
  es2021: true
  node: true
extends: plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "react/prop-types": "off",
  "@typescript-eslint/ban-ts-comment": "off"
}
settings:
  react:
    pragma: "React"
    version: "detect"
