FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci && cat package.json package-lock.json | sha256sum | cut -d ' ' -f1 > node_modules/.package-lock.sha256

COPY . .

EXPOSE 9000

CMD ["sh", "./docker-entrypoint.dev.sh"]
